# CloudEngine ~ PHP + Node.JS
language: php

php:
  - 7.0
  #- 5.6

git:
  depth: 8

before_install:
  - nvm install v6
  - node -v
  - npm -v

install:
  - travis_retry composer install --no-interaction
  - travis_retry composer npm-install

script:
  - composer validate --no-interaction
  - composer test

# End.
