# CloudEngine ~ PHP + Node.JS

language: php

php: 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

git:
  depth: 8

before_install: nvm install v8

install:
  - composer install
  - composer npm-install

before_script: composer validate

script: composer test

# End.
