# CloudEngine ~ PHP + Node.JS

language: php

php: 7.0

git:
  depth: 8

before_install:
  - nvm install v6
  - npm -v

install:
  - composer install
  - composer npm-install

before_script: composer validate

script: composer test

# End.
